//
// Copyright © 2024 Stream.io Inc. All rights reserved.
//

import Foundation
import MCP

/// A protocol for types that can process actions produced by a client tool.
/// Conforming types receive one or more `ClientToolAction` values generated as
/// the result of a tool invocation and decide how they should be applied or executed.
public protocol ClientToolActionHandling: AnyObject {

    /// Handles a list of actions generated by a client tool.
    ///
    /// - Parameter actions: An array of `ClientToolAction` instances describing work
    ///   that should be performed, such as emitting events, updating state, or
    ///   triggering additional client-side behavior.
    func handle(_ actions: [ClientToolAction])
}

/// A registry responsible for storing and managing all client tools available
/// to the Model Context Protocol (MCP) runtime. This class handles registration,
/// lookup, and routing of invocation requests to the appropriate tool instance.
public final class ClientToolRegistry {

    /// Internal storage mapping tool names to their corresponding `ClientTool` instances.
    private var toolsByName: [String: any ClientTool] = [:]

    /// Creates a new, empty tool registry.
    public init() {}

    /// Registers a client tool in the registry, making it discoverable by name.
    ///
    /// - Parameter tool: The tool to register. The registry uses the name defined in
    ///   `tool.toolDefinition.name` as the lookup key.
    public func register(tool: any ClientTool) {
        toolsByName[tool.toolDefinition.name] = tool
    }

    /// Produces the set of registration payloads for all registered tools. These
    /// payloads are used by the MCP runtime to understand the name, description,
    /// input schema, and behavior of each tool.
    ///
    /// - Returns: An array of `ToolRegistrationPayload` describing each registered tool.
    public func registrationPayloads() -> [ToolRegistrationPayload] {
        toolsByName.values.map { tool in
            ToolRegistrationPayload(
                name: tool.toolDefinition.name,
                description: tool.toolDefinition.description ?? tool.instructions,
                instructions: tool.instructions,
                parameters: tool.toolDefinition.inputSchema,
                showExternalSourcesIndicator: tool.showExternalSourcesIndicator
            )
        }
    }

    /// Routes an invocation request to the appropriate tool based on its name.
    /// If the referenced tool does not exist, an empty action array is returned.
    ///
    /// - Parameter invocation: The `ClientToolInvocation` containing the tool name
    ///   and invocation arguments.
    /// - Returns: A list of actions produced by the tool, or an empty array if the
    ///   requested tool is not registered.
    public func handleInvocation(_ invocation: ClientToolInvocation) -> [ClientToolAction] {
        guard let tool = toolsByName[invocation.tool.name] else { return [] }
        return tool.handleInvocation(invocation)
    }
}

/// A protocol representing a client-side tool that can be invoked by the Model Context Protocol (MCP) runtime.
/// Conforming types define how a tool is described, when it should be displayed, and how it responds to invocations.
public protocol ClientTool: AnyObject {

    /// The static definition of the tool, including its name, parameters, and behavior
    /// as communicated to the MCP runtime. This is used by the system to surface the tool
    /// in the model’s available capabilities.
    var toolDefinition: Tool { get }

    /// Additional usage instructions or human-readable guidance that may be shown to users
    /// or the MCP runtime. This supplements the tool definition with contextual tips on
    /// how or when the tool should be used.
    var instructions: String { get }

    /// A Boolean value indicating whether the runtime should show a UI indicator when the tool
    /// relies on external data sources. When `true`, the client may visually signal that calls
    /// to this tool interact with systems outside the local model context.
    var showExternalSourcesIndicator: Bool { get }

    /// Handles an invocation of the tool from the MCP runtime. Implementations should inspect
    /// the incoming invocation payload, perform the necessary work, and return one or more
    /// `ClientToolAction` values describing the results or follow-up actions.
    ///
    /// - Parameter invocation: The invocation request containing arguments and metadata provided by the runtime.
    /// - Returns: A list of actions describing the tool’s response to the invocation.
    func handleInvocation(_ invocation: ClientToolInvocation) -> [ClientToolAction]
}

/// Represents a client-side invocation of a tool, including the tool's metadata
/// and any arguments provided by the Model Context Protocol (MCP) runtime.
public struct ClientToolInvocation {

    /// A descriptor containing metadata about a tool being invoked.
    public struct ToolDescriptor {

        /// The unique name of the tool being invoked.
        let name: String

        /// A human-readable description of the tool, if provided.
        let description: String?

        /// Additional instructions or usage guidance associated with the tool.
        let instructions: String?

        /// The raw-encoded input parameter schema for the tool, typically encoded as JSON.
        let parameters: Data?

        /// Creates a new tool descriptor.
        ///
        /// - Parameters:
        ///   - name: The unique identifier of the tool.
        ///   - description: A user-facing description of the tool.
        ///   - instructions: Supplementary guidance about how to use the tool.
        ///   - parameters: Raw input schema data, if available.
        public init(
            name: String,
            description: String?,
            instructions: String?,
            parameters: Data?
        ) {
            self.name = name
            self.description = description
            self.instructions = instructions
            self.parameters = parameters
        }
    }

    /// Metadata describing the tool being invoked.
    public let tool: ToolDescriptor

    /// The raw arguments associated with the invocation, typically encoded as JSON.
    public let args: Data?

    /// An optional message identifier associated with the context of the invocation.
    /// This may be used to correlate tool responses to originating messages.
    public let messageId: String?

    /// An optional channel identifier indicating the source or conversational
    /// context in which the invocation occurred.
    public let channelId: AnyHashable?

    /// Creates a new tool invocation containing metadata and raw arguments.
    ///
    /// - Parameters:
    ///   - tool: The descriptor of the tool being invoked.
    ///   - args: Raw encoded arguments supplied for the invocation.
    ///   - messageId: The ID of the associated message, if any.
    ///   - channelId: A channel or thread identifier for contextual routing.
    public init(
        tool: ToolDescriptor,
        args: Data?,
        messageId: String?,
        channelId: AnyHashable?
    ) {
        self.tool = tool
        self.args = args
        self.messageId = messageId
        self.channelId = channelId
    }
}

/// A type representing an action produced by a client tool. Actions are expressed
/// as closures that will be executed by whichever component is responsible for
/// handling `ClientToolAction` values.
///
/// Tool implementations generate actions to signal that client-side behavior
/// should occur—such as updating UI, emitting events, or triggering follow-up logic.
public typealias ClientToolAction = () -> Void

/// A payload describing a tool to the MCP runtime during registration.
/// This structure encapsulates the metadata, usage instructions, parameter schema,
/// and optional UI behaviors associated with the tool.
public struct ToolRegistrationPayload: Encodable {

    /// The unique name of the tool. This is how the MCP runtime identifies it.
    public let name: String

    /// A user-facing description summarizing the tool's purpose and behavior.
    public let description: String

    /// Optional instructional text offering additional guidance about how or
    /// when to use the tool.
    public let instructions: String?

    /// The tool's expected input parameter schema encoded as a `Value`.
    /// This describes the shape of the arguments the tool accepts.
    public let parameters: Value?

    /// Indicates whether the client UI should display an indicator when the tool
    /// interacts with external data sources.
    public let showExternalSourcesIndicator: Bool?
}
